≈≈name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name="报告生成器" generate_reports_cross_platform.py
        
    - name: Prepare release package
      run: |
        mkdir release
        copy dist\报告生成器.exe release\
        mkdir release\reports_input
        copy reports_input\* release\reports_input\
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: reports-generator
        path: release/
        
    # 自动发布版本(可选)
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/报告生成器.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
